### ISSUE TITLE
feature: specify loadpath for tests?

### ISSUE THREAD

**Issue by perezd** [cloudkick/whiskey#1]
It'd be nice if there was -i or something for me to specify the loadpath for my require statements, much like the node executable itself.

**Comment by Kami** [comment]
So basically you want an option which would preppend all the specified paths to the `require.paths` array?

If you only need to specify a "base directory" for your tests so you can use relative imports in your tests and code, you can use the `--chdir` option - https://github.com/cloudkick/whiskey/blob/master/lib/constants.js#L63

**Comment by perezd** [comment]
I tried this but it still seems to not work as you've specified :( --chdir "./lib" lib "lib" __dirname+/lib I've tried a bunch of versions of this.

**Comment by Kami** [comment]
Yeah, it needs to be an absolute path :)

For example `--chdir "/home/user/my_app/lib/`
