### ISSUE TITLE
assert.response example

### ISSUE THREAD

**Issue by dandean** [cloudkick/whiskey#12]
Hello! I'd really love to see an example of how assert.response works -- I'm trying to get it to work, but having zero luck. Even rudimentary documentation would really be appreciated.

Thanks!

**Comment by Kami** [comment]
Yeah, sorry, we are working on adding some docs.

In the mean time you can find some assert.response examples here - https://github.com/cloudkick/cast/blob/develop/tests/simple/http-bundles.js#L148.
