### ISSUE TITLE
Test All the files in a folder

### ISSUE THREAD

**Issue by arunoda** [cloudkick/whiskey#24]
Lets say my tests files are located at 'tests' folder.
There are thousands of test files out there. How should I test them with a single bash command?

**Comment by Kami** [comment]
Hi, you can use something like this:

``` bash

TEST_FILES=$(find tests -name '*.js' |  tr \\r\\n ,)

whiskey --tests "$TEST_FILES"
```

**Comment by arunoda** [comment]
How about integration this into the core.
like
`whiskey tests/"

cheers

2011/9/8 Tomaž Muraus <
reply@reply.github.com>

> Hi, you can use something like this:
> 
> `bash
> 
> TEST_FILES=$(find tests -name '*.js' |  tr \r\n ,)
> 
> whiskey --tests "$TEST_FILES"
> `
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cloudkick/whiskey/issues/24#issuecomment-2039115

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Kami** [comment]
Multiple people have already asked about this and I think for now you can use tools such as `find` which are more flexible then a built-in solution would probably be.

In any case, having some kind of test auto-discovery would be nice (nose Python test runner has a test discovery feature which is pretty cool).

Also keep in mind that having a test auto-discovery feature is not the same as allowing users to pass paths for the `--test` argument, but it's semi-related.

**Comment by arunoda** [comment]
Got it.
If someone did a pull request on this will you accept it (I think you are
one of the maintainer of the project)

thanks.

2011/9/8 Tomaž Muraus <
reply@reply.github.com>

> Multiple people have already asked about this and I think for now you can
> use tools such as `find` which are more flexible then a built-in solution
> would probably be.
> 
> In any case, having some kind of test auto-discovery would be nice (nose
> Python test runner has a test discovery feature which is pretty cool).
> 
> Also keep in mind that having a test auto-discovery feature is not the same
> as allowing users to pass paths for the `--test` argument, but it's
> semi-related.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cloudkick/whiskey/issues/24#issuecomment-2040109

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Kami** [comment]
Yeah, pull request would be a good start :)

**Comment by arunoda** [comment]
Great. I'll try to do it :) Since I'm a pretty big nodeunit user and found
that it's not maintaining properly. So whiskey suites me well.
Hope you guyes are maintaining it :)

thanks.

2011/9/8 Tomaž Muraus <
reply@reply.github.com>

> Yeah, pull request would be a good start :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cloudkick/whiskey/issues/24#issuecomment-2040398

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
