### ISSUE TITLE
How to test with Code Coverage

### ISSUE THREAD

**Issue by arunoda** [cloudkick/whiskey#25]
Hi Can someone please point me out how to do code coverage with whiskey

**Comment by Kami** [comment]
For example:

`NODE_PATH=lib-cov/ whiskey --tests "<your test files>" --coverage --coverage-reporter cli`

You also need to have `node-jscoverage` installed.

**Comment by arunoda** [comment]
if the Src files are on `lib` folder. 
I've to require them as
  require('module');

intested of
 require('../lib/module');

am I correct?

**Comment by Kami** [comment]
Correct.

The problem is that it won't really work if you use relative imports (`require('../lib/bar')`). To make it work for cases like this I would need to hook into the require system.

**Comment by arunoda** [comment]
Got it.
And If I written some tests with code coverage.
Those tests cannot be used without code coverage and it prompts an error
(require error)

2011/9/13 Tomaž Muraus <
reply@reply.github.com>

> Correct.
> 
> The problem is that it won't really work if you use relative imports
> (`require('../lib/bar')`). To make it work for cases like this I would need
> to hook into the require system.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cloudkick/whiskey/issues/25#issuecomment-2074242

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Kami** [comment]
I'm not totally sure what is your question.

You can use it without the code coverage. node-jscoverage will just instrument all of the code in `lib/` directory and copy the instrument code into the `lib-cov/` directory.
