### ISSUE TITLE
Coverage output of missed lines

### ISSUE THREAD

**Issue by devdazed** [cloudkick/whiskey#31]
Right now the coverage only output the number of lines tested and missed.  Can you also make an option to output the lines of code actually missed.  I think expresso does this.

**Comment by Kami** [comment]
This is available in json and html coverage reporter.

It makes little sense to include that in the cli reporter if you have more than a few files.

**Comment by devdazed** [comment]
this is exactly what i need.  i didnt realize the html reporter had everything.  thanks!
