### ISSUE TITLE
Ability to throttle test concurrency?

### ISSUE THREAD

**Issue by perezd** [cloudkick/whiskey#4]
I have a feeling my tests are saturating my CouchDB instance, I am getting test errors that occur only when I run the entire suite as a group, in isolation things run fine. Is there a setting I can use to throttle the test runners a bit?

**Comment by Kami** [comment]
Yes, it is possible that this is happening because too many tests run at the same time.

In general, test files run sequentially, but all the tests in a single file run concurrently.

I will add a `--concurrency` option in the next release.

**Comment by Kami** [comment]
Support for `--concurrency` option has been added to just released Whiskey 0.3.0.

**Comment by perezd** [comment]
So, just to be clear, is --concurrency per file? or test within file? Feels like per file.

**Comment by Kami** [comment]
The limit is per tests in a file.

Test files itself run in series, not in parallel :)

I will add better explanation to the docs soon.
