### ISSUE TITLE
hide passed tests, require asserts, print expected and actual

### ISSUE THREAD

**Issue by btipling** [cloudkick/whiskey#48]
Just a note about a couple of features I'd like to add as a patch some time:
1. I'd like to hide pass tests via command line argument.
2. I'd like to print the actual and expected inputs in the error report.
3. I'd like to be able to tell a test how many asserts to expect and to error out if it doesn't get that many.

Just things I want to add at some point.

**Comment by Kami** [comment]
All of this features sound reasonable to me and patches are very welcome.

Number 1 will probably end up being command line switch which is fine. At some point will need to do something with regards to the command line options though. Currently Whiskey already has many different options which makes it harder to use and not so user friendly.

**Comment by Kami** [comment]
@btipling do let us / me know if you have any questions.

**Comment by Kami** [comment]
(cleaning up the old issues)

@btipling is this still relevant or can I close this issue?

**Comment by Kami** [comment]
Closing old and non-relevant ticket. If this becomes relevant again, please open a new issue / pull request.
