### ISSUE TITLE
Support for --teamcity reporter

### ISSUE THREAD

**Issue by voronianski** [cloudkick/whiskey#65]
mocha has cool support for teamcity reporter, it should not be hard to port it to whisky.

btw as I understand using mocha as bdd framework with whiskey is not a good solution?

**Comment by Kami** [comment]
@voronianski A while ago, @robert-chiniquy added support for it so Whiskey itself does have some support for BDD idioms (https://github.com/cloudkick/whiskey/blob/master/lib/bdd.js, https://github.com/cloudkick/whiskey/blob/master/example/test-bdd.js),

**Comment by voronianski** [comment]
@Kami cool, but what about teamcity?

**Comment by Kami** [comment]
@voronianski I just had a look (https://github.com/rdingwall/mocha/blob/6ac1c811435fa2065f0c7852298d8b04727ca9aa/lib/reporters/teamcity.js) and yes, it should be easy to port it.

If you want to take a stab, go for it. You can find an existing Whiskey test reporter here - https://github.com/cloudkick/whiskey/blob/master/lib/reporters/test/cli.js

**Comment by voronianski** [comment]
@Kami cool, i will take a look on it :)

**Comment by Kami** [comment]
@voronianski Awesome - let us know if you get stuck or need help :)

**Comment by Kami** [comment]
(cleaning up the old issues)

@voronianski is this still relevant or can I close this issue?

**Comment by Kami** [comment]
@voronianski Thanks for closing the issue. If you ever change your mind or feel like implementing this, feel free to open a new issue :)
