### ISSUE TITLE
get "TIMEOUT" when testing with cassandra?

### ISSUE THREAD

**Issue by baolinCloud** [cloudkick/whiskey#70]
my code is easy:

---

exports.testCassandra = function(test, assert) {
    var cql = require('node-cassandra-cql');
    var client = new cql.Client({hosts: ['127.0.0.1:9042'], keyspace: 'schema1'});
    client.execute('SELECT user_id, email FROM users WHERE user_id=?', ['baby'] ,function(err, result) {
          // baby's email is test@google.com    in  cassandra ;  
           assert.equal("test@google.com", result.rows[0].email);  
  });
    test.finish();
};

---

when i run " whiskey -t testCassandra.js", display "OK "  but "TIMEOUT".

Is there anything wrong  with my configuration or my test case?

**Comment by Kami** [comment]
Couple of things.
1. You get a timeout because you never close a connection to cassandra. You should do this inside the execute callback.
2. You should also move test.finish inside the execute callback.

**Comment by baolinCloud** [comment]
Thanks a lot  !

**Comment by Kami** [comment]
No problem.
