### ISSUE TITLE
add test.disable()/test.ignore() ability 

### ISSUE THREAD

**Issue by perezd** [cloudkick/whiskey#8]
would be nice to have the ability within a setUp method to specify that the tests in this file should be ignored because of some environmental condition that would be checked and then asserted. Using test.ignore/disable would not effect the exit code, it would also provide the ability to specify why it was ignored, to be sent to stdout:

`test.ignore('server was not running.')`

the logs would print [IGNORED] in the same place you see [TIMEOUT] and [OK]

**Comment by pquerna** [comment]
Maybe call this test.skip() and show [SKIPPED] -- seems more accurate than ignored?

**Comment by perezd** [comment]
yeah, I like that too. I am not sure what the right language is, but I think one of these makes sense.

**Comment by Kami** [comment]
Merged into master in ac60a15083d09d10d0da6732ee58f53ffcd95244.

Will be available in the next release.

**Comment by perezd** [comment]
Awesome work!
